### ISSUE TITLE
Light Client Rust related follow up

### ISSUE THREAD

**Issue by ebuchman** [interchainio/tendermint-rs#110]
Replacement for elements of #96 more specific to Rust implementation style and architecture.

We should update the ADR with the relevant changes from here as well.

Types:
- [x] Make `validate_vals_and_commit` a method on Commit (https://github.com/interchainio/tendermint-rs/pull/84#discussion_r358019467)
- [x] Use `validate_next_vals` !
- [ ] Introduce a `Client` type to hold `Store` and `Requester` (?)  (https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360484471)
- [ ] Put `trust_threshold` and `trusting_period` in the Store (?) (https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360484471)
- [ ] Enforce off-by-one issues in the type system, eg.:
    - [ ] `TrustedState::new` taking header h-1 and validators for h (https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360338190)
    - [ ] `verify` taking vals for the right height (https://github.com/interchainio/tendermint-rs/pull/100)
- [x] make `trust_level` satisfy Copy or Clone and don't pass by reference (https://github.com/interchainio/tendermint-rs/pull/100)
- [ ] memoize results of methods that don't take args, eg. `.hash()` (https://github.com/interchainio/tendermint-rs/issues/96#issuecomment-567003346)
- [ ] use an enum for height to get the latest state instead of special-casing 0 (#118)
- [ ] introduce a simple event type and let bisection function (or a Client structure it's a method on) take a closure that will fire events. this can be used for logging so we don't need a print statement or logger inside the functions

Module Structure:
- [ ] Remove dependency on `tendermint` types, eg. `Hash`
- [ ] Make it a crate ? 
- [ ] Rename types.rs to interface.rs (https://github.com/interchainio/tendermint-rs/pull/100#issuecomment-567903975)
- [ ] Add example to doc 
- [x] Simplify the public API and make it harder/impossible to use incorrectly
- [x] Unexpose verify_single once json tests are updated (https://github.com/interchainio/tendermint-rs/pull/114/commits/525c89f2fc2a352b889f3aad674d74bbeb3dd98c#diff-f0c5bdd887eaf26a3fd9ec5bdc93e2d9R106 and https://github.com/interchainio/tendermint-rs/pull/114/commits/9fbb749ea91b7e3af5178ff13aa194eeb793a59b#diff-afc724a3f81219fadc771326ccca3a84R8)

Errors:
- [ ] `Error::RequestFailed` should wrap underlying requester errors (https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360341870)
- [ ] Deduplicate the `Error::InvalidSignature` with `ErrorKind::SignatureInvalid`
- [ ] Move to an error.rs file 
- [ ] voting_power_in can't detect signatures from validators not in the current validator set (can't detect signatures from validators not in the current validator set)
- [x] need two distinct errors for InsufficientVotingPower - one when it's insufficient to skip (ie. so do bisection) and one when it's insufficient to verify (ie. return error) #119

**Comment by ebuchman** [comment]
With respect to module structure, I would say there are a few goals:

- isolate concerns
- minimize dependencies
- keep trait implementations in a single place 

The last point is to make it clear where to look for say all the implementations of the `lite` traits. Right now they're spread out across the `tendermint` crate.

So I think this suggests we try to eliminate the dependency of `lite` on tendermint data types (currently only Height and Hash), and to eliminate the dependency of `tendermint` on `lite`, and then move the implementations to their own small crate. Ie. we might have the following crates:

- `tendermint`
  - the current tendermint crate, but without the `lite` module or any of the implementations of traits in the `lite` module
- `lite`
  - the current lite module - just traits and functionality. uses no `tendermint` types
- `tendermint-lite`
  - implements the `lite` traits using `tendermint` types. To be used by the light node and by IBC
- `tendermint-lite-node`
  - abscissa application using the `tendermint-lite` implementation and the verify functions from `lite` to actually implement a node that performs syncing

The independence of `tendermint-lite` may seem excessive, but this is basically the set of common features (both tendermint and lite client logic) that both the light node and IBC will utilize.

Thoughts?

This also relates to https://github.com/interchainio/tendermint-rs/issues/7#issuecomment-529067141 which proposes high level crate structure for this repo.

**Comment by ebuchman** [comment]
Re @xla review on #114 (https://github.com/interchainio/tendermint-rs/pull/114#pullrequestreview-337408027) - consider not passing the `store` into the light client verify functions. See discussion in https://github.com/interchainio/tendermint-rs/pull/114#discussion_r362251100

Also consider renamings:
- [ ] `verify_and_update_bisection` -> `update_bisection`
- [ ] `_verify_and_update_bisection` -> `verify_and_update_bisection`

**Comment by ebuchman** [comment]
Few more points from discussion after latest review https://github.com/interchainio/tendermint-rs/pull/114#pullrequestreview-338058645:

- [ ]  ensure that time in headers is monotonic, ie. `untrusted_header.bft_time() > trusted_header.bft_time()` in `verify_single`
- [ ] check that the blockchain is not ahead of our local clock, ie. `untrusted_header.bft_time() < now + X` for every header we fetch

In theory, if we check that time is monotonic,  we only need to check that the highest height we're trying to sync to is not ahead of our local clock (ie. we don't need to check this for every header, since all the other headers are less than the highest one). However, if we only check for monotonic time after we've trusted a pivot header, its possible we would trust a pivot header who's time is too far ahead of our local clock, and hence might be outside the trusting period.

**Comment by Liamsi** [comment]
> verify_and_update_bisection -> update_bisection

This is only cool, if we also rename `verify_and_update_single` to `update_single`. I've renamed:
`verify_and_update_bisection` -> `verify_and_update_bisection_inner` in 31550c3

**Comment by Liamsi** [comment]
> Re @xla review on #114 (#114 (review)) - consider not passing the store into the light client verify functions. See discussion in #114 (comment)

If we don't pass in the `store` but a `trusted_state` instead, we won't store all the intermediate headers that we requested in between. The only things we can store is the final new trusted state. I think logic-wise this shouldn't be a problem but we need test and verify this too. The go-client stores all the headers it trusts in between (the pivot-headers and -vals). Again, we need to update the spec accordingly.

**Comment by ebuchman** [comment]
Looks like that concern is resolved in #132 now by returning the list of all bisected headers. That PR addressed a bunch of these issues. I think it's time to close this issue and open a few new ones to capture the remaining points.

**Comment by ebuchman** [comment]
Some points turn out not to be relevant or necessary. Everything else is addressed or followed up in #136, #137, #138, #139, #140
