### ISSUE TITLE
Light client impl followup 

### ISSUE THREAD

**Issue by Liamsi** [interchainio/tendermint-rs#96]
Tracking TODOs for the Light client impl

Feedback / Review of #84 
 - [x] Move additional checks  to `validate_vals_and_commit` and make it function of `Commit`(?): https://github.com/interchainio/tendermint-rs/pull/84#discussion_r358019467 - done in #109
 - [ ] redundant check for sigs: https://github.com/interchainio/tendermint-rs/pull/84#discussion_r358018987, https://github.com/tendermint/spec/pull/61#discussion_r358015568
 - [ ] https://github.com/interchainio/tendermint-rs/pull/84#discussion_r358008529 (and general organizational issues: e.g. crate vs module etc)
   - remove dependencies on tendermint types (account::Id, Hash)
- [ ] add example to doc: https://github.com/interchainio/tendermint-rs/pull/84#discussion_r357989612
- [x] `From<SystemTimeEror> for lite::Error` and  https://github.com/interchainio/tendermint-rs/pull/84#discussion_r358017746. Done in #109
- [x] https://github.com/interchainio/tendermint-rs/pull/84#discussion_r358018000 (return OK?) - Done in #109
- [x] remove `Validator` trait ? https://github.com/interchainio/tendermint-rs/pull/84#discussion_r358018253 - done in #105 
- [x] how to handle if/when votes don't contain validator id? probably worth discussing in separate issue: https://github.com/interchainio/tendermint-rs/pull/84#discussion_r358008934 - done, added a comment in #109 
- [ ] next steps: https://github.com/interchainio/tendermint-rs/pull/84#issuecomment-565229546
- [ ] rename types.rs to interface.rs - https://github.com/interchainio/tendermint-rs/pull/100#issuecomment-567903975 
- [ ] consider Client type and have can_trust be a method on the Client. Also put trust_threshold and trusting_period in the trusted state? https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360484471
- [ ] enforce off-by-one issues in the type system if possible, eg. TrustedState::new taking header h-1 and validators for h. https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360338190. Also verify taking vals for the right height https://github.com/interchainio/tendermint-rs/pull/100/#discussion_r360493104.
- [ ] Error::RequestFailed should wrap underlying requester errors. https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360341870
- [ ] Improve naming of variables like `h1_xxx` and `h2`. This should also be done simultaneously with the spec. eg. https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360342976 and https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360343926 and https://github.com/interchainio/tendermint-rs/pull/100/files#r360479080
- [ ] how to get latest height from a node? use height=0 ? https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360470376. Could get rid of get_smaller_or_equal (https://github.com/interchainio/tendermint-rs/pull/100). Need to do with spec.
- [ ] improve logic of check_support to better clarify the 3 conditions: ok (update state), real error (faulty node or system), not-enough-voting-power (not real error, just need to bisect)
- [ ] make trust_level satisfy Copy or Clone and don't pass by reference https://github.com/interchainio/tendermint-rs/pull/100/#discussion_r360480140

**Comment by Liamsi** [comment]
Something else I've noticed, and we can optimize for (but later): Currently all operations on the impls of traits traits that do not take an additional argument can be "cached" in a field instead of recomputed on each call.
In particular `Header::hash`: https://github.com/interchainio/tendermint-rs/blob/24955d18a99f3f3a846f519b770de5887159a0fa/tendermint/src/block/header.rs#L98
and `ValidatorSet` hash: https://github.com/interchainio/tendermint-rs/blob/24955d18a99f3f3a846f519b770de5887159a0fa/tendermint/src/validator.rs#L33
At least currently the API does only allow to create these structs without modifying them.  These hashes could be computed once instead of on every call of `hash()`.

**Comment by ebuchman** [comment]
With respect to removing the Validator trait. I think this is something we should try to do, since these methods aren't actually used within the light client itself, they only need to be exposed so that an implementation of Commit.voting_power_in, which takes a ValidatorSet, has access to these validator internals. Perhaps we can avoid this if the ValidatorSet is somehow an associated type on Commit so it can more readily access the internals without going through a trait. 

This will also make it much easier to write tests for the core light client logic without having to mock out individual validators and the `verify_signature` method

**Comment by ebuchman** [comment]
Ok, some of these are addressed in #100 and #109, as noted in the edited opening post. The rest are split up into issues #110, #111, and #112 for things related to Rust, the spec, and the next steps, respectively :). Closing this for all those.
